stages:
    - build
    - test

rustfmt:
    stage: build
    tags:
        - docker
    image: rustlang/rust:nightly
    script:
        - rustup component add rustfmt-preview
        - cargo fmt -- --write-mode diff

build dynamic binary on stable:
    stage: build
    tags:
        - docker
    image: rust:latest
    script:
        - cargo build --verbose
    artifacts:
        name: "$CI_JOB_NAME"
        paths:
            - Cargo.toml
            - Cargo.lock

build dynamic binary on nightly:
    stage: build
    tags:
        - docker
    image: rustlang/rust:nightly
    script:
        - cargo build --verbose
    allow_failure: true
    artifacts:
        name: "$CI_JOB_NAME"
        paths:
            - Cargo.toml
            - Cargo.lock

build static binary:
    stage: build
    tags:
        - rust-cross
    script:
        - cross build --target x86_64-unknown-linux-musl --release
        - cp target/x86_64-unknown-linux-musl/release/i3nator i3nator
    artifacts:
        name: "$CI_JOB_NAME"
        paths:
            - Cargo.toml
            - Cargo.lock
            - i3nator

test dynamic binary on stable:
    stage: test
    tags:
        - docker
    image: rust:latest
    dependencies: []
    script:
        - cargo test -- --nocapture
        - cargo test -j1 --features sequential-tests -- --test-threads 1 --nocapture

test dynamic binary on nightly:
    stage: test
    tags:
        - docker
    image: rustlang/rust:nightly
    dependencies: []
    script:
        - cargo test -- --nocapture
        - cargo test -j1 --features sequential-tests -- --test-threads 1 --nocapture
    allow_failure: true

test static binary:
    stage: test
    tags:
        - rust-cross
    dependencies: []
    script:
        - cross test --target x86_64-unknown-linux-musl -- --nocapture
        - cross test --target x86_64-unknown-linux-musl -j1 --features sequential-tests -- --test-threads 1 --nocapture
