sign-commit = true
tag-name = "{{version}}"

# Handle new section in CHANGELOG.md
# 1. Replace the fields in the unreleased header.
[[pre-release-replacements]]
file = "CHANGELOG.md"
search = "## Unreleased"
replace = "## {{version}} ({{date}})"
exactly = 1
prerelease = false
# 2. Add a new unreleased header.
[[pre-release-replacements]]
file = "CHANGELOG.md"
search = "<!-- next-header -->"
replace = "<!-- next-header -->\n\n## Unreleased"
exactly = 1
prerelease = false
