# i3nator project

# General configuration items
[general]
# Working directory to use
working_directory = "/path/to/my/working/directory"

# Name of the workspace the layout should be applied to
workspace = "1"

# Path to your layout-file
layout_path = "/path/to/my/layout.json"

# Alternatively, you can include the JSON-contents of the layout directly:
# layout = "{ ... }"

# List of applications to start
[[applications]]
command = "mycommand --with 'multiple args'"
working_directory = "/path/to/a/different/working/directory"
