# i3nator project

# General configuration items
[general]
# Working directory to use (this is optional)
working_directory = "/path/to/my/working/directory"

# Name of the workspace the layout should be applied to (this is optional, if
# not specified, the active workspace will be used)
workspace = "1"

# Path to your layout-file
layout_path = "/path/to/my/layout.json"

# Alternatively, you can include the JSON-contents of the layout directly:
# layout = """
# {
#     ...
# }"""

# List of applications to start
[[applications]]
# Command to run to start the application
command = "mycommand --with 'multiple args'"
# Different working directory to use (optional)
# working_directory = "/path/to/a/different/working/directory"
