name: cargo-bloat

on:
  pull_request:
    branches:
    - master
    paths:
    - '**/Cargo.toml'
    - '**/Cargo.lock'

jobs:
  cargo-bloat:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Retrieve cache
      uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-bloat-${{ hashFiles('**/Cargo.lock') }}

    - name: Install Rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        override: true

    - name: cargo bloat
      uses: orf/cargo-bloat-action@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
