name: cargo-audit

on:
  pull_request:
    paths:
    - '**/Cargo.toml'
    - '**/Cargo.lock'

jobs:
  cargo-audit:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: cargo audit
      # TODO: reenable the "offical" audit-check once its core-version is upgraded
      # uses: actions-rs/audit-check@v1
      uses: pitkley/actions-rs-audit-check@temp/use-own-core
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
