name: Prepare release

on:
  push:
    tags:
    - '[0-9]+.[0-9]+.[0-9]+'
    - '[0-9]+.[0-9]+.[0-9]+-*'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Retrieve cache
      uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-ci-${{ hashFiles('**/Cargo.lock') }}
    - name: Install Rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        override: true

    - name: cargo build --release
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: --release
      env:
        TARGET: x86_64-unknown-linux-musl
    - name: Create checksum
      run: |
        sha256sum target/release/i3nator > target/release/i3nator.sha256

    - name: Identify if tag is a prerelease
      id: tag
      run: |
        if [[ "${{ github.ref }}" =~ ^refs/tags/(.+)$ ]]; then
          echo "::set-output name=value::${BASH_REMATCH[1]}"
        else
          echo "::error ::Expected a tag"
          exit 1
        fi

        if [[ "${{ github.ref }}" =~ ^refs/tags/[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
          echo "::set-output name=is-prerelease::false"
        else
          echo "::set-output name=is-prerelease::true"
        fi
    - name: Prepare release
      id: prepare-release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: v${{ github.ref }}
        draft: true
        prerelease: ${{ steps.tag.outputs.is-prerelease }}
        body: |
          # Summary

          TODO!

          ## Changes

          TODO!

          ## Installation

          You have multiple options to install i3nator:

          1. Download the static binary from this release. This will work without any additional dependencies.

          2. If you have at least Rust 1.38.0 with Cargo installed, you can install i3nator directly from crates.io:

              ```console
              $ cargo install i3nator
              ```

              If you are updating i3nator through cargo, just use:

              ```console
              $ cargo install --force i3nator
              ```

              In case you want to install this specific version, you can specify the `--vers` argument:

              ```console
              $ cargo install --force --vers ${{ steps.tag.outputs.value }} i3nator
              ```

          3. Another option is to install from directly from source (this again requires at least Rust 1.38.0):

              ```console
              $ git clone https://github.com/pitkley/i3nator.git
              $ cd i3nator
              $ cargo install
              ```

          **Note:** If you want to be able to use the automatic command execution feature, you will need to install [`xdotool`][xdotool].

          [xdotool]: https://github.com/jordansissel/xdotool

    - name: Upload static i3nator binary
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.prepare-release.outputs.upload_url }}
        asset_path: target/release/i3nator
        asset_name: i3nator-x86_64-unknown-linux-musl
        asset_content_type: application/octet-stream
    - name: Upload static i3nator binary checksum
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.prepare-release.outputs.upload_url }}
        asset_path: target/release/i3nator.sha256
        asset_name: i3nator-x86_64-unknown-linux-musl.sha256
        asset_content_type: application/octet-stream
